version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:18

    working_directory: ~/leonarpv-astro

    steps:
      - checkout

      - run:
          name: Install Dependencies
          command: pnpm 

      - save_cache:
          key: v1-npm-deps-{{ checksum "pnpm-lock.yaml" }}
          paths:
            - ./node_modules
      - run:
          name: Astro Build
          command: pnpm build

      - run:
          name: Firebase Deploy
          command: ./node_modules/.bin/firebase deploy --token "$FIREBASE_TOKEN"
